### ISSUE TITLE
Whakawairua Tuahu missing from the list

### ISSUE THREAD

**Issue by fakeaccount1234** [MatisLepik/poe-checklist#4]
As per title.
Connected to Strand - T4

**Comment by fakeaccount1234** [comment]
Ok I just looked further down the list and saw it was listed below. It is incorrectly listed as a T6 though.

**Comment by MatisLepik** [comment]
Thanks, fixed. There may be some higher tier uniques that have an incorrect tier as well. I'll update them if I complete them on the atlas
