### ISSUE TITLE
Crafting recipes?

### ISSUE THREAD

**Issue by tehKaiN** [MatisLepik/poe-checklist#7]
Basically content from [this](https://xanthics.github.io/poe_craftingrecipes/) page - I don't like to use that page because it saves stuff in URL instead of local storage. And yours has very clean UI. This way your checklist will become one to rule them all. ;)

**Comment by MatisLepik** [comment]
That would be nice indeed - but it's a lot of data to collect manually, and I don't want to take data from the project you've linked. If there's a reliable place to scrape this from, I'll consider it.

Note that they're changing the UI ingame, so this may not be as necessary in 3.6:

> The Crafting Bench now displays all mods, not just the mods you have unlocked. Mods you have not yet unlocked are greyed out.

**Comment by tehKaiN** [comment]
Yes, but I doubt in-game UI will display where one can acquire it.

Regarding data source - [Poedb](https://poedb.tw/CraftingBenchOptions) has this info from somewhere, and by quick glimpse into page's source I see it's loaded dynamically - can't quickly find from where it's getting loaded, but locating file's URL and syncing your project's data with its contents from time to time wouldn't be a bad idea, I think.

Regarding data files from project that I linked - it's MIT-licensed, so I think it'd be okay to borrow data, apart from the fact that it's probably out of date by now. I see it's [JSON-encoded](https://github.com/xanthics/poe_craftingrecipes/blob/master/recipes.py) - perhaps fetching data from poedb could be done in such way that it'd generate file usable for both projects?

**Comment by tehKaiN** [comment]
I think this is not needed anymore since PoE UI shows where one can unlock recipes when hovering mouse on them.
